# Generated by Django 4.2.3 on 2023-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_garage_car_car_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='name',
            field=models.CharField(default='Garage', max_length=100),
        ),
    ]
