# Generated by Django 4.2.3 on 2023-08-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rent_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
