# Generated by Django 4.2.3 on 2023-08-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_driver_car_remove_driver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='address',
            new_name='curent_city',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='country',
        ),
    ]
