# Generated by Django 4.2.3 on 2023-08-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_curent_city_driver_current_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rent'),
            preserve_default=False,
        ),
    ]
