# Generated by Django 4.2.3 on 2023-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_review_rating_car_rating_driver_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.IntegerField(default=0),
        ),
    ]
