# Generated by Django 4.2.3 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_car_total_trips_driver_total_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
