# Generated by Django 4.2.3 on 2023-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rent_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seat',
            field=models.IntegerField(default=4),
        ),
    ]
